name: Notify Success

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20.11.0" # Should run on node versions released after this is created.

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  notify-success:
    runs-on: ubuntu-latest
    needs: test
    if: ${{success()}} && needs.test.result == 'success'

    steps:
      - name: Send Discord Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_TEST_FAILS }}
          status: Success
          title: "Run Tests"
          description: "Runs all of the tests that are defined in the package.json"
          url: "https://github.com/Trickje/NAS/actions/workflows/runtests.yml"
          username: "Github.com/Trickje/NAS: Run Tests"
          color: 0x00ff00
