name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20.11.0" # Should run on node versions released after this is created.

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
